using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Euler;

namespace UnitTests
{
    [TestClass]
    public class UnitTest3
    {
        [TestMethod]
        public void TestAmicableNumbers()
        {
            int upTo = 10000;
            var task = new Task21();
            Assert.AreEqual(31626, task.Run(upTo), $"Amicable numbers sum up to {upTo} is incorrect");
        }

        [TestMethod]
        public void TestNamesScores()
        {
            var task = new Task22();
            Assert.AreEqual(871198282, task.Run(), $"The total of all the name scores in the file is incorrect");
        }

        [TestMethod]
        public void TestNonAbundantSums()
        {
            var task = new Task23();
            Assert.AreEqual(4179871, task.Run(), $"The sum of all the positive integers which cannot be written as the sum of two abundant numbers is incorrect");
        }

        [TestMethod]
        public void TestLexicographicPermutations()
        {
            int availableDigits = 10;
            int permutationNumber = 1000000;
            var task = new Task24(availableDigits);
            Assert.AreEqual(2783915460, task.Run(permutationNumber), $"The {permutationNumber} lexicographic permutation of the digits is is incorrect");
        }

        [TestMethod]
        public void Test1000DigitFibonacciNumber()
        {
            int digitsNumber = 1000;
            var task = new Task25();
            Assert.AreEqual(4782, task.Run(digitsNumber), $"The { digitsNumber}-digit Fibonacci number is {task.Run(digitsNumber)}");
        }

        [TestMethod]
        public void TestReciprocalCycles()
        {
            int maxNumber = 1000;
            var task = new Task26();
            Assert.AreEqual(983, task.Run(maxNumber), $"The value of d < {maxNumber} for which 1/d contains the longest recurring cycle in its decimal fraction part is {task.Run(maxNumber)}");
        }

        [TestMethod]
        public void TestQuadraticPrimes()
        {
            int aMax = 1000, bMax = 1000;
            var task = new Task27();
            Assert.AreEqual(-59231, task.Run(aMax, bMax), $"The quadratic expression that produces the maximum number of primes for consecutive values of n is {task.Run(aMax, bMax)}");
        }

        [TestMethod]
        public void TestNumberSpiralDiagonals()
        {
            int rows = 1001;
            var task = new Task28();
            Assert.AreEqual(669171001, task.Run(rows), $"The sum of the numbers on the diagonals in a {rows} by {rows} spiral is {task.Run(rows)}");
        }

        [TestMethod]
        public void TestDistinctPowers()
        {
            int maxA = 100, maxB = 100;
            var task = new Task29();
            Assert.AreEqual(9183, task.Run(maxA, maxB), $"Distinct terms are in the sequence generated by ab for 2 ≤ a ≤ {maxA} and 2 ≤ b ≤ {maxB} is {task.Run(maxA, maxB)}");
        }

        [TestMethod]
        public void TestDigitFifthPowers()
        {
            var task = new Task30();
            Assert.AreEqual(443839, task.Run(), $"The sum of all the numbers that can be written as the sum of fifth powers of their digits is {task.Run()}");
        }

        [TestMethod]
        public void TestCoinSums()
        {
            int sum = 200;
            var task = new Task31();
            Assert.AreEqual(73682, task.Run(sum), $"£2 can be made using any number of coins in different ways");
        }
    }
}
